Yevgen_Dmytriyev/Yevgen_Dmytriyev/urls.py
from django.contrib import admin
from django.urls import include, path
from files import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('files.urls', 'files'), namespace='main')),
]

Yevgen_Dmytriyev/files/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('work/', views.work, name='work'),
    path('skills/', views.skills, name='skills'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
]

Yevgen_Dmytriyev/files/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
    
class HomePageContent(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title")
    content = models.TextField(verbose_name="Content")

    class Meta:
        verbose_name = "Home Page Content"
        verbose_name_plural = "Home Page Contents"

    def __str__(self):
        return self.title

Yevgen_Dmytriyev/files/forms.py
from django import forms
from django.core.validators import EmailValidator


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.CharField(validators=[EmailValidator()])
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    

Yevgen_Dmytriyev/files/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.utils.translation import gettext as _
from django.core.mail import EmailMessage
from django.conf import settings

def index(request):
    context = {
        'title': _('Home'),
    }
    return render(request, 'main/index.html', context)

def work(request):
    context = {
        'title': _('My work'),
        'content': _("""
        Secure-Zen

        A comprehensive solution for the analysis and detection of malicious files and links,
        available as web, mobile, and desktop applications. The project is aimed at providing
        a high level of security for end-users and organizations.

        Main Components:
        Programming Language: Python.
        Web Framework: Django.
        Frontend: HTML, CSS, JavaScript.
        Application: Development of the server side, application logic, interaction with the database,
        and API integration.
        Databases: PostgreSQL.
        API Integration: For data exchange between client applications and the server.
        Application Versions:
        Web Version: Provides a user interface through a browser. Based on Django and uses HTML, CSS,
        and JavaScript for the frontend.
        Mobile Application: Developed for major mobile platforms (iOS, Android).
        Desktop Application: For Windows, macOS, and Linux.
        """),
    }
    return render(request, 'main/work.html', context)


def contact(request):
    context = {
        'title': _('Contact Information'),
        # 'content': _(
        #     "Address: Potsdam, Germany\n"
        # )
    }
    
    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        message = request.POST.get('message', '')
        
        subject = 'New message from user {}, for Yevgen'.format(name)
        message_body = '{} has sent you a new message:\n\nName: {}\nEmail: {}\nMessage:\n{}'.format(name, name, email, message)
        
        try:
            email = EmailMessage(
                subject,
                message_body,
                settings.EMAIL_HOST_USER,
                [settings.EMAIL_HOST_USER],  # Assuming you want to send the email to yourself
            )
            email.send()
            messages.success(request, _('Thank you! Your message has been sent.'))
        except Exception as e:
            print(f"Error sending email: {e}")
            messages.error(request, _('An error occurred: ') + str(e))
            return redirect('main:contact')
        
        return redirect(reverse('main:contact'))  # Redirect the user to the contact page

    return render(request, 'main/contact.html', context)

def skills(request):
    context = {
        'title': _('My skills'),
        'content': _("""
            Technologies
            HTML
            CSS
            Python
            Object-Oriented Programming (OOP)
            Google Cloud Platform (GCP)
            Amazon Web Services (AWS)
            CI/CD
            REST API

            Databases
            Relational Database Management System (RDBMS)
            SQL & PostgreSQL

            Version Controls
            GitHub

            Frameworks
            Django

            Others
            Agile Development Project Management
        """)
    }
    return render(request, 'main/skills.html', context)

def about(request):
    context = {
        'title': _('About'),
        'content': _("""
            Hello, I'm Yevgen and I am a Python Backend Developer.
        As a Python developer who enjoys tackling technical challenges, 
        I've dedicated the past year to studying hard and honing my skills. 
        I take pride in building things properly and ensuring client satisfaction.
        My goal is to join a tech company where I can apply my knowledge 
        to solve innovative problems. I'm enthusiastic about developing 
        top-notch backend systems, not settling for mediocrity. 
        I'm seeking a position that offers opportunities to work on
        intricate projects, learn from industry experts, and 
        contribute to advancing technology for collective success.
        """)
    }
    return render(request, 'main/about.html', context)

    

Yevgen_Dmytriyev/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block body_class %}class="about-page"{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
<!-- Your custom styles can go here if not in a separate CSS file -->
{% endblock %}

{% block content %}
<!-- Inline style for background -->
<div class="container mt-5 pt-5">
    <h3 class="text-left text-black"><strong>{{ title }}</strong></h3>
    <h3 class="text-left text-black"><strong>{{ content |linebreaks }}</strong></h3>
    <!-- Add this line for the resume download link -->
    <a href="{% static 'deps/images/Yevgen_Dmytriyev_CV.pdf' %}" download="Yevgen_Dmytriyev_CV.pdf" class="download-button">
        Download My Resume
    </a>
</div>
{% endblock %}

Yevgen_Dmytriyev/templates/main/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="{% get_current_language as LANGUAGE_CODE %}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'deps/css/bootstrap/bootstrap.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    <!-- Favicon -->
    <link rel="icon" href="{% static 'deps/favicon/favicon.ico' %}" type="image/x-icon">
    <title>{% block title %}{% trans 'Home' %}{% endblock %}</title>
    <style>
        .animated-text {
            cursor: pointer;
            font-size: 180px;
            font-weight: bold;
            text-align: center;
            transition: color 0.1s ease;
            margin-top: 120px;
            line-height: 0.35em;
        }
        .page-container {
            transition: transform 0.5s ease;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="page-container">
            {% block fixed-content %}
                <h1>
                    <div class="container">
                        <div id="hello" class="animated-text" style="color: #f0f0f0; text-align: left; margin-left: -120px;">Hello</div>
                        <div id="world" class="animated-text" style="color: #f0f0f0; text-align: left; margin-left: -120px;">World</div>
                        <div id="im" class="animated-text" style="color: #000; text-align: left; margin-left: -120px;">I am</div>
                        <div id="kate" class="animated-text" style="color: #000; text-align: left; margin-left: -120px;">Yevgen</div>
                    </div>
                </h1>
            {% endblock %}
            {% block page-contentainer %}
                {% block content %}
                {% endblock %}
            {% endblock %}
        </div>
    </div>

    {% block scripts %}
        <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
        <script>

            document.querySelectorAll('.animated-text').forEach(element => {
                const originalText = element.textContent; // Store the original text for each element
            
                element.addEventListener('mouseover', function() {
                    // Change text based on the element's id
                    switch (element.id) {
                        case 'hello':
                            element.textContent = '{% trans "About"%}';
                            break;
                        case 'world':
                            element.textContent = '{% trans "Skills"%}';
                            break;
                        case 'im':
                            element.textContent = '{% trans "Work"%}';
                            break;
                        case 'kate':
                            element.textContent = '{% trans "Contact" %}';
                            break;
                    }
                });
            
                element.addEventListener('mouseout', function() {
                    // Revert to the original text if not clicked
                    element.textContent = originalText;
                });
            
                element.addEventListener('click', function() {
                    // Define URL mappings
                    const urlMap = {
                        'About': '{% url "main:about" %}',
                        'Skills': '{% url "main:skills" %}',
                        'Work': '{% url "main:work" %}',
                        'Contact': '{% url "main:contact" %}',
                    };
                    // Navigate based on the current text content
                    window.location.href = urlMap[element.textContent];
                });
            });
        </script>
    {% endblock %}
</body>
</html>

Yevgen_Dmytriyev/templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block body_class %}class="contact-page"{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5 pt-5">
    <h3 class="text-left text-black"><strong>{{ title }}</strong></h3>
    {% comment %} <h3 class="text-left text-white"><strong style="text-shadow: 2px 2px 4px #000;">{{ content |linebreaks }}</strong></h3> {% endcomment %}
    <p class="text-left text-black">
        <div class="address">
            <img src="{% static 'deps/icons/address.png' %}" alt="Address" class="icon address-icon">
            <span class="address-text text-black">Berlin, Germany</span>
        </div>
    </p>
    <p class="text-left text-black">
        <div class="phone">
            <img src="{% static 'deps/icons/phoneaddress.png' %}" alt="Phone" class="icon phone-icon">
            <span class="phone-text text-black">+49 162 47 76 735</span>
        </div>
    </p>
    <p class="text-left text-black">
        <div class="social-icons">
            <a href="mailto:dmitrievevgenii@gmail.com" class="email-link">
                <span class="email-icon">
                    <img src="{% static 'deps/icons/email.png' %}" alt="Email" class="email-icon">
                </span>
            </a>
            <a href="https://github.com/YevgenDmytriyev" class="github-link">
                <img src="{% static 'deps/icons/github.png' %}" alt="GitHub" class="github-icon">
            </a>
            <a href="http://www.linkedin.com/in/yevgen-dmytriyev-7457b2285/" class="linkedin-link">
                <img src="{% static 'deps/icons/linkedin.png' %}" alt="LinkedIn" class="linkedin-icon">
            </a>
        </div>
    </p>
    
    <form action="{% url 'main:contact' %}" method="POST" class="u-clearfix u-form-spacing-24 u-form-vertical u-inner-form" style="padding: 0px;">
        {% csrf_token %}
        <div class="u-form-group u-form-name">
            <label for="name" class="u-form-control-hidden u-label"></label>
            <input type="text" placeholder="{% trans 'Enter your Name' %}" id="name" name="name" class="u-input u-input-rectangle" required="">
        </div>
        <div class="u-form-group u-form-email">
            <label for="email" class="u-form-control-hidden u-label"></label>
            <input type="email" placeholder="{% trans 'Enter a valid email address' %}" id="email" name="email" class="u-input u-input-rectangle" required="">
        </div>
        <div class="u-form-group u-form-message">
            <label for="message" class="u-form-control-hidden u-label"></label>
            <textarea placeholder="{% trans 'Enter your message' %}" rows="4" cols="50" id="message" name="message" class="u-input u-textarea" required=""></textarea>
        </div>
        <div class="u-form-group u-align-left u-form-submit">
            <button type="submit" id="submitBtn" class="u-btn u-btn-submit u-button-style u-btn-1" style="background-color: black; color: #ffffff; border: none; text-transform: uppercase;">{% trans 'Submit' %}</button>
        </div>
    </form>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

Yevgen_Dmytriyev/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block body_class %}class="index-page"{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
<link rel="stylesheet" href="{% static 'deps/css/styles.css' %}">
<style>
    .animated-text {
        cursor: pointer;
        font-size: 180px;
        transition: color 0.1s ease;
        margin: 10px;
        display: inline-block;
    }
    .animated-text:hover {
        color: #3498db; /* Change as needed */
    }
</style>
{% endblock %}

<body>
    <div class="container mt-5">
        <div class="page-container">
            {% block fixed-content %}
                <h1>
                    <div class="container">
                        <div id="hello" class="animated-text" style="color: #f0f0f0; text-align: left; margin-left: -120px;">Hello</div>
                        <div id="world" class="animated-text" style="color: #f0f0f0; text-align: left; margin-left: -120px;">World</div>
                        <div id="im" class="animated-text" style="color: #000; text-align: left; margin-left: -120px;">I am</div>
                        <div id="kate" class="animated-text" style="color: #000; text-align: left; margin-left: -120px;">Yevgen</div>
                    </div>
                </h1>
            {% endblock %}
            {% block page-contentainer %}
                {% block content %}
                {% endblock %}
            {% endblock %}
        </div>
    </div>

    {% block scripts %}
        <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
        <script>
            document.querySelectorAll('.animated-text').forEach(element => {
                const originalText = element.textContent; // Store the original text for each element
            
                element.addEventListener('mouseover', function() {
                    // Change text based on the element's id
                    switch (element.id) {
                        case 'hello':
                            element.textContent = '{% trans "About"%}';
                            break;
                        case 'world':
                            element.textContent = '{% trans "Skills"%}';
                            break;
                        case 'im':
                            element.textContent = '{% trans "Work"%}';
                            break;
                        case 'kate':
                            element.textContent = '{% trans "Contact" %}';
                            break;
                    }
                });
            
                element.addEventListener('mouseout', function() {
                    // Revert to the original text if not clicked
                    element.textContent = originalText;
                });
            
                element.addEventListener('click', function() {
                    // Define URL mappings
                    const urlMap = {
                        'About': '{% url "main:about" %}',
                        'Skills': '{% url "main:skills" %}',
                        'Work': '{% url "main:work" %}',
                        'Contact': '{% url "main:contact" %}',
                    };
                    // Navigate based on the current text content
                    window.location.href = urlMap[element.textContent];
                });
            });
        </script>
    {% endblock %}
</body>

Yevgen_Dmytriyev/templates/main/skills.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block body_class %}class="skills-page"{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
<!-- Your custom styles can go here if not in a separate CSS file -->
{% endblock %}

{% block scripts %}
<!-- Ensure jQuery is properly loaded -->
<script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
<script>
    jQuery(document).ready(function($) {
        $('.skillbar').each(function() {
            $(this).find('.skillbar-bar').animate({
                width: $(this).attr('data-percent')
            }, 3000);
        });
    });
</script>
<script>
    document.querySelectorAll('.animated-text').forEach(element => {
        const originalText = element.textContent; // Store the original text for each element
    
        element.addEventListener('mouseover', function() {
            // Change text based on the element's id
            switch (element.id) {
                case 'hello':
                    element.textContent = '{% trans "About"%}';
                    break;
                case 'world':
                    element.textContent = '{% trans "Skills"%}';
                    break;
                case 'im':
                    element.textContent = '{% trans "Work"%}';
                    break;
                case 'kate':
                    element.textContent = '{% trans "Contact" %}';
                    break;
            }
        });
    
        element.addEventListener('mouseout', function() {
            // Revert to the original text if not clicked
            element.textContent = originalText;
        });
    
        element.addEventListener('click', function() {
            // Define URL mappings
            const urlMap = {
                'About': '{% url "main:about" %}',
                'Skills': '{% url "main:skills" %}',
                'Work': '{% url "main:work" %}',
                'Contact': '{% url "main:contact" %}',
            };
            // Navigate based on the current text content
            window.location.href = urlMap[element.textContent];
        });
    });
</script>
{% endblock %}

{% block content %}
<div class="container mt-5 pt-5">
    <h3 class="text-left text-black"><strong>{{ title }}</strong></h3>
    <ul>
        <li>
            <p class="wide text-black">Python</p>
            <div class="back skillbar clearfix" data-percent="90%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:50%;">90%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">Object-Oriented Programming (OOP)</p>
            <div class="back skillbar clearfix" data-percent="75%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:50%;">75%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">Django</p>
            <div class="back skillbar clearfix" data-percent="70%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:50%">70%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">SQL & PostgreSQL</p>
            <div class="back skillbar clearfix" data-percent="80%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:50%">80%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">HTML, CSS, JS</p>
            <div class="back skillbar clearfix" data-percent="75%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:50%">75%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">REST API</p>
            <div class="back skillbar clearfix" data-percent="55%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:70%">55%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">Amazon Web Services (AWS)</p>
            <div class="back skillbar clearfix" data-percent="80%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:50%">80%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">Google Cloud Platform (GCP)</p>
            <div class="back skillbar clearfix" data-percent="70%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:50%">70%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">CI/CD</p>
            <div class="back skillbar clearfix" data-percent="50%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:70%">50%</div>
            </div>
        </li>
        <li>
            <p class="wide text-black">GitHub</p>
            <div class="back skillbar clearfix" data-percent="85%">
                <div class="skill skillbar-bar text-black" style="height:28px;width:50%">85%</div>
            </div>
        </li>
    </ul>
</div>
{% endblock %}

Yevgen_Dmytriyev/templates/main/work.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block body_class %}class="work-page"{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
<!-- Your custom styles can go here if not in a separate CSS file -->
{% endblock %}

{% block content %}
<div class="container mt-5 pt-5"> <!-- Added mb-5 for margin-bottom -->
        <h3 class="text-left text-black"><strong>{{ title }}</strong></h3>
        <h3 class="text-left text-black"><strong>{{ content |linebreaks }}</strong></h3>
</div>
{% endblock %}